// This file is auto-generated by scripts/generate-audio-manifests.mjs
export const safetyManifest = [
  {
    "file": "shift-start.wav",
    "label": "Shift Start"
  },
  {
    "file": "stay_alert.wav",
    "label": "Stay Alert"
  },
  {
    "file": "stay-hydrated.wav",
    "label": "Stay Hydrated"
  },
  {
    "file": "tip_conveyor_safety.wav",
    "label": "Tip Conveyor Safety"
  },
  {
    "file": "tip_feels_unsafe.wav",
    "label": "Tip Feels Unsafe"
  },
  {
    "file": "tip_hair_and_clothing.wav",
    "label": "Tip Hair And Clothing"
  },
  {
    "file": "tip_know_your_limit.wav",
    "label": "Tip Know Your Limit"
  },
  {
    "file": "tip_report_unsafe_conditions.wav",
    "label": "Tip Report Unsafe Conditions"
  },
  {
    "file": "tip_stretch_and_hydrate.wav",
    "label": "Tip Stretch And Hydrate"
  },
  {
    "file": "tip_use_gloves.wav",
    "label": "Tip Use Gloves"
  }
] as const;
